# Site settings
title: "Your awesome title"
description: >-
  A minimal math blog using the Cayman theme.
baseurl: ""
url: ""

# Build settings
theme: "jekyll-theme-cayman"     # â† use the local gem theme
plugins:
  - jekyll-feed                 # match any plugins you have in the Gemfile
